### ISSUE TITLE
Block UI after Payment

### ISSUE THREAD

**Issue by AppcDevSon** [hansemannn/ti.paypal#2]
I'm using paypal module in a navigation window, if I clicked on cancel or completed the payment, the payment UI is closed but all buttons in my navigation window are blocked and I can't click on them, I think it is because the payment UI is opened in modal window, is there a way to fix this?

**Comment by hansemannn** [comment]
Hey @SoniaAbed, I just pushed some changes to the dialog to be opened on the right thread and also updated to the latest PayPal-SDK. Please check the 1.0.2 version draft in the Releases tab. Thanks!

**Comment by AppcDevSon** [comment]
@hansemannn thank you, I tested the new version and I'm still getting the same problem.

**Comment by hansemannn** [comment]
Please share a simplified test-case that reproduces the bug, thanks!

**Comment by AppcDevSon** [comment]
I had to remove the paypal module from the app to be able to upload the file, please add it before running the code. The app freeze after completing or canceling the payment and I can't click on any button, and sometimes it don't freeze until after I leave the window containing the payment button or clicking pay with paypal 2 times...

Thank you so much for your help

**Comment by AppcDevSon** [comment]
@hansemannn were you able to reproduce the error? is there anything I can help with?

**Comment by hansemannn** [comment]
I did not have time to look into it, yet, sorry!

**Comment by AppcDevSon** [comment]
No problem I'm using an old module for now

**Comment by eolverabea** [comment]
Hello, the cancel button does not work , ie not close the window, and at the time of payment does not return any event.

**Comment by hansemannn** [comment]
I just pushed an attempt that could fix both issues. Please try latest master or [this module](https://www.dropbox.com/s/d3bq9w3nky3pty5/ti.paypal-iphone-1.0.2.zip?dl=1).

**Comment by eolverabea** [comment]
Hello try this version and the result is the same, thanks for you 's feedback , the testing 'm doing in sanbox

**Comment by eolverabea** [comment]
[video.zip](https://github.com/hansemannn/ti.paypal/files/430862/video.zip)

sending this video

**Comment by ericpolkadoc** [comment]
has this been resolved yet?

**Comment by hansemannn** [comment]
Just pushed some more changes, please try [this build](https://www.dropbox.com/s/d3bq9w3nky3pty5/ti.paypal-iphone-1.0.2.zip?dl=1). Not many more ideas.

**Comment by ericpolkadoc** [comment]
will do -- will let you know how it goes

**Comment by quocbao1087** [comment]
Hi Hans,
I tested in sandbox. Simple payment.
The paymentDidComplete doesn't always get called.

**Comment by hansemannn** [comment]
@ericpolkadoc just said it works for him now. What's about @SoniaAbed and @eolverabea, does it work for you now? Then I would public the final version asap. Thanks!

**Comment by AppcDevSon** [comment]
@hansemannn it works for me the first time then when I leave the window and try to go back to it the app is stuck and I can't click any button, I'm testing using the example I sent before

**Comment by eolverabea** [comment]
Only works once , then it's the same

**Comment by AshKernsworth** [comment]
Same here. Works fine unless you cancel out, navigate away from the current view then try to return.

**Comment by hansemannn** [comment]
I am still not able to reproduce it. Can you try the [1.1.0-beta.1](https://github.com/hansemannn/ti.paypal/releases/tag/ios-1.1.0) prerelease I just drafted? Otherwise I will create a demo-app again and debug it in detail. Thanks!

**Comment by eolverabea** [comment]
I tried it on an actual device and I appeared this error:
[WARN] :   osname: iphone
[WARN] :   -canOpenURL: failed for URL: "org-appextension-feature-password-management://" - error: "This app is not allowed to query for scheme org-appextension-feature-password-management"

**Comment by hansemannn** [comment]
@eolverabea how is this related to this issue and/or even to the module? If you want to use 1Password, try https://github.com/hansemannn/ti.onepassword

**Comment by eolverabea** [comment]
@hansemannn  When I use the module in shed some mistakes devices stop working before, this was one of them.

**Comment by hansemannn** [comment]
I mean, you obviously need the 1password URL-schemes if you want to enable 1Password in Paypal (if they use it there):

``` xml
<ios>
    <plist>
        <dict>
            <key>LSApplicationQueriesSchemes</key>
            <array>
            <string>org-appextension-feature-password-management</string>
            </array>
        </dict>
    </plist>
</ios>
```

But I don't see how this is related to the actual UI-blocking issue.

**Comment by eolverabea** [comment]
the same mistake does not always appear when you load the module PayPal, the error appeared only once when I load the module

**Comment by eolverabea** [comment]
according to this issue the warning may be interfering with a library or something in code that cause the application to freeze.

https://github.com/paypal/PayPal-iOS-SDK/issues/459

**Comment by hansemannn** [comment]
From what I read in the linked Github issue, it might help to place the init into the `open` event of your Window. And @eolverabea did you place the `org-appextension-feature-password-management` correctly? Please attach your (obfuscated) tiapp.xml.

**Comment by hansemannn** [comment]
I was just able to reproduce the issues and pushed major fixes right now. I am now not able to reproduce it anymore and will draft the 1.2.0 version in a second. Thx!

**Comment by hansemannn** [comment]
https://github.com/hansemannn/ti.paypal/releases/tag/ios-1.2.0

**Comment by AppcDevSon** [comment]
I tested the new release and when I click open with paypal nothing happens the after a few seconds the app close. is there anything I should change in the Paypal settings? (I'm using the example code I uploaded before)

**Comment by hansemannn** [comment]
@SoniaAbed You commented out required properties like `merchantPrivacyPolicyURL` and `merchantUserAgreementURL` , added event-listeners after showing the dialog and created a new PayPal instance in every view you created. This will mess-up the SDK-scope and cause unhandled problems. Please fix that and everything will work.
